### ISSUE TITLE
Index Error in classification_lexicase example

### ISSUE THREAD

**Issue by eduardomadeira98** [alcides/GeneticEngine#112]
```
Traceback (most recent call last):
  File "/Users/eduardomadeira/Documents/lasige/GeneticEngine/examples/classification_lexicase.py", line 218, in <module>
    ClassificationLexicaseBenchmark().main(seed=0)
  File "/Users/eduardomadeira/Documents/lasige/GeneticEngine/examples/classification_lexicase.py", line 211, in main
    best = alg.evolve()
  File "/Users/eduardomadeira/Documents/lasige/GeneticEngine/geneticengine/algorithms/gp/gp.py", line 115, in evolve
    population = self.step.iterate(
  File "/Users/eduardomadeira/Documents/lasige/GeneticEngine/geneticengine/algorithms/gp/operators/combinators.py", line 96, in iterate
    [
  File "/Users/eduardomadeira/Documents/lasige/GeneticEngine/geneticengine/algorithms/gp/operators/combinators.py", line 97, in <listcomp>
    step.iterate(
  File "/Users/eduardomadeira/Documents/lasige/GeneticEngine/geneticengine/algorithms/gp/operators/combinators.py", line 30, in iterate
    population = step.iterate(
  File "/Users/eduardomadeira/Documents/lasige/GeneticEngine/geneticengine/algorithms/gp/operators/selection.py", line 94, in iterate
    best_fitness = choose_best([x.get_fitness(problem).fitness_components[c] for x in candidates_to_check])
  File "/Users/eduardomadeira/Documents/lasige/GeneticEngine/geneticengine/algorithms/gp/operators/selection.py", line 94, in <listcomp>
    best_fitness = choose_best([x.get_fitness(problem).fitness_components[c] for x in candidates_to_check])
IndexError: list index out of range
```

this occurs because the length of the number of cases is higher than the length of the individual's list of fitnesses
number of cases - 1000
length of the individual list of fitnesses - 750 

maybe an assertion is needed to make sure that the length  of the individual fitnesses list is equal to the number of cases, to prevent other index errors in the future

**Comment by eduardomadeira98** [comment]
solved in the commit fa692572836e00e48a1b97089d3ee4062c81b2f6
