### ISSUE TITLE
Access phenotype of an individual with a GrammaticalEvolution representation

### ISSUE THREAD

**Issue by PedroBarbosa** [alcides/GeneticEngine#117]
Hi,

My code breaks when using GE representation.  I'm posting below a reproducible example of a grammar that uses a Metahandler to generate strings containing DNA nucleotides.

```
from __future__ import annotations
from abc import ABC
from dataclasses import dataclass
from typing import Annotated
from geneticengine.algorithms.gp.individual import Individual

from geneticengine.core.grammar import Grammar, extract_grammar
from geneticengine.core.random.sources import RandomSource, Source
from geneticengine.core.representations.grammatical_evolution.ge import GrammaticalEvolutionRepresentation
from geneticengine.metahandlers.base import MetaHandlerGenerator

class RandomDNA(MetaHandlerGenerator):

    def __init__(self, size: int):

        self.size = size
        self.nucelotides = ["A", "C", "G", "T"]
        
    def generate(
        self,
        r: Source,
        g: Grammar,
        rec,
        new_symbol,
        depth: int,     
        base_type,
        context: dict[str, str],
    ):
        
        sequence = "".join(r.random.choices(self.nucleotides, k=self.size))
        rec(sequence)

class Root(ABC):
    pass

@dataclass  
class Leaf(Root):
    letters: Annotated[str, RandomDNA(size=3)]

r = RandomSource(seed=1)
g = extract_grammar([Leaf], Root)
rep = GrammaticalEvolutionRepresentation(g, max_depth=2)  
ind = Individual(genotype=rep.create_individual(r=r, g=g), genotype_to_phenotype=rep.genotype_to_phenotype)

print(ind.get_phenotype())

Traceback (most recent call last):
  File "/workspaces/generativeSplicing/test.py", line 44, in <module>
    print(ind.get_phenotype())
  File "/workspaces/generativeSplicing/GeneticEngine/geneticengine/algorithms/gp/individual.py", line 31, in get_phenotype
    self.phenotype = self.genotype_to_phenotype.get()(self.genotype)
  File "/workspaces/generativeSplicing/GeneticEngine/geneticengine/core/representations/grammatical_evolution/ge.py", line 150, in genotype_to_phenotype
    return create_tree(
  File "/workspaces/generativeSplicing/GeneticEngine/geneticengine/core/representations/grammatical_evolution/ge.py", line 80, in create_tree
    return random_node(rand, g, depth, g.starting_symbol, initialization_mode)
  File "/workspaces/generativeSplicing/GeneticEngine/geneticengine/core/representations/tree/treebased.py", line 40, in random_node
    return method(r, g, max_depth, starting_symbol)
  File "/workspaces/generativeSplicing/GeneticEngine/geneticengine/core/representations/tree/initializations.py", line 194, in pi_grow_method
    expand_node(
  File "/workspaces/generativeSplicing/GeneticEngine/geneticengine/core/representations/tree/initializations.py", line 269, in expand_node
    apply_metahandler(
  File "/workspaces/generativeSplicing/GeneticEngine/geneticengine/core/representations/tree/initializations.py", line 39, in apply_metahandler
    return metahandler.generate(
  File "/workspaces/generativeSplicing/test.py", line 30, in generate
    sequence = "".join(r.random.choices(self.nucleotides, k=self.size)) # type: ignore
AttributeError: 'ListWrapper' object has no attribute 'random'
```

**Comment by alcides** [comment]
I don't see any bug here. Your example is wrong in two places:

- typo in the name of the nucleotide field.
- You are calling a random field (and corresponding choices) that does not exist in the Random API. 

Where did you find examples of such usage (choices)?

A right version of the example is here: https://github.com/alcides/GeneticEngine/blob/ab68550797686448117f284ce2156fb02280d570/tests/representations/ge/ge_test.py

**Comment by PedroBarbosa** [comment]
My bad. I was able to reproduce your test now.

> Where did you find examples of such usage (choices)?

Not in geneticEngine, but in my project the following metahandler has been working to generate random nucleotides with a given probability:

```
class RandomNucleotides(MetaHandlerGenerator):
    """
    RandomNucleotides(s) generates a random string of s nucleotides
    sampled from the expected GC content frequency in the human genome
    """

    def __init__(self, size: int):

        assert size > 0, "size must be > 0"
        self.size = size
        self.freq = {"A": 0.3, "C": 0.2, "G": 0.2, "T": 0.3}
        
    def generate(
        self,
        r: Source,
        g: Grammar,
        rec,
        new_symbol,
        depth: int,     
        base_type,
        context: dict[str, str],
    ):

        nucleotides = list(self.freq.keys())
        weights = list(self.freq.values())
        sequence = "".join(r.random.choices(nucleotides, weights=weights, k=self.size)) # type: ignore
        rec(sequence)

    def __repr__(self):
        return f"RandomNucleotides[n={self.size}]"
```

**Comment by alcides** [comment]
Accessing `r.random` works for TreeBased-only, and it's not guaranteed to work in future versions. The API of things you can access is what is defined in the Source class.

**Comment by PedroBarbosa** [comment]
Ok. Will update the code accordingly.
