### ISSUE TITLE
GPFriendly bugs

### ISSUE THREAD

**Issue by eduardomadeira98** [alcides/GeneticEngine#77]
###### first bug

the following code :
```
alg = GPFriendly(
        ...
        representation=TreeBasedRepresentation,
        ...
        initialization_method= "ramped",
        ...
   )
```
raises an AssertionError in line 162 of GPFriendly  
``` if initialization_method == "ramped": assert isinstance(representation, TreeBasedRepresentation) ``` 
and I believe it shouldnt raise that error because the assertion condition is true

###### second bug

the following code:
```
alg = GPFriendly(
        ...
        representation=StructuredGrammaticalEvolutionRepresentation,
        ...
    )
```
raises a KeyError ``` KeyError: ' ' ```  inside the structured_ge.py file, line 100 in randint method
Is StructuredGrammaticalEvolutionRepresentation depending on another GPFriendly argument to work??

**Comment by eduardomadeira98** [comment]
I tried to replicate the second bug yesterday, and it was running fine, no errors. But today I tried again and I had the same error as before. I will assume that probably it's something wrong with my venv.

**Comment by eduardomadeira98** [comment]
```
(.venv) eduardomadeira@MacBook-Pro-de-Eduardo examples % python3 classification.py 
Grammar<Starting=Number,Productions=[Number -> Plus(left: Number, right: Number)|Mul(left: Number, right: Number)|SafeDiv(left: Number, right: Number)|Literal(val: Annotated)|Var(name: Annotated)|SafeSqrt(number: Number)|SafeLog(number: Number)]>
Traceback (most recent call last):
  File "/Users/eduardomadeira/Documents/lasige/GeneticEngine/examples/classification.py", line 169, in <module>
    b, bf = evolve(g, 123, False)
  File "/Users/eduardomadeira/Documents/lasige/GeneticEngine/examples/classification.py", line 162, in evolve
    (b, bf, bp) = alg.evolve()
  File "/Users/eduardomadeira/Documents/lasige/.venv/lib/python3.10/site-packages/GeneticEngine-0.0.30-py3.10.egg/geneticengine/algorithms/gp/gp.py", line 96, in evolve
  File "/Users/eduardomadeira/Documents/lasige/.venv/lib/python3.10/site-packages/GeneticEngine-0.0.30-py3.10.egg/geneticengine/algorithms/gp/operators/combinators.py", line 28, in iterate
  File "/Users/eduardomadeira/Documents/lasige/.venv/lib/python3.10/site-packages/GeneticEngine-0.0.30-py3.10.egg/geneticengine/algorithms/gp/operators/selection.py", line 46, in iterate
  File "/Users/eduardomadeira/Documents/lasige/.venv/lib/python3.10/site-packages/GeneticEngine-0.0.30-py3.10.egg/geneticengine/algorithms/gp/operators/selection.py", line 48, in <lambda>
  File "/Users/eduardomadeira/Documents/lasige/.venv/lib/python3.10/site-packages/GeneticEngine-0.0.30-py3.10.egg/geneticengine/algorithms/gp/individual.py", line 33, in evaluate
  File "/Users/eduardomadeira/Documents/lasige/.venv/lib/python3.10/site-packages/GeneticEngine-0.0.30-py3.10.egg/geneticengine/algorithms/gp/individual.py", line 28, in get_phenotype
  File "/Users/eduardomadeira/Documents/lasige/.venv/lib/python3.10/site-packages/GeneticEngine-0.0.30-py3.10.egg/geneticengine/core/representations/grammatical_evolution/structured_ge.py", line 173, in genotype_to_phenotype
  File "/Users/eduardomadeira/Documents/lasige/.venv/lib/python3.10/site-packages/GeneticEngine-0.0.30-py3.10.egg/geneticengine/core/representations/grammatical_evolution/structured_ge.py", line 116, in create_tree
  File "/Users/eduardomadeira/Documents/lasige/.venv/lib/python3.10/site-packages/GeneticEngine-0.0.30-py3.10.egg/geneticengine/core/representations/tree/treebased.py", line 39, in random_node
  File "/Users/eduardomadeira/Documents/lasige/.venv/lib/python3.10/site-packages/GeneticEngine-0.0.30-py3.10.egg/geneticengine/core/representations/tree/initializations.py", line 202, in pi_grow_method
  File "/Users/eduardomadeira/Documents/lasige/.venv/lib/python3.10/site-packages/GeneticEngine-0.0.30-py3.10.egg/geneticengine/core/random/sources.py", line 57, in pop_random
  File "/Users/eduardomadeira/Documents/lasige/.venv/lib/python3.10/site-packages/GeneticEngine-0.0.30-py3.10.egg/geneticengine/core/representations/grammatical_evolution/structured_ge.py", line 100, in randint
KeyError: ''
```

**Comment by alcides** [comment]
Fixed in https://github.com/alcides/GeneticEngine/commit/aa55abc2ce0f3329013ab6faa9178334fd767fec
